name: task-a cd

on:
  pull_request:
    paths:
      - "task_a/**"

jobs:
  test:
    name: pytest (${{ matrix.os }} / ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "pypy3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.10"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r ./task_a/requirements.txt

      - name: Run tests
        run: |
          pip install pytest pytest-html
          pytest ./task_a/task_a.py --html=report.html --self-contained-html

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Report-${{ matrix.os }}-${{ matrix.python-version }}
          path: report.html

        