name: task-a cd

on: [push]

jobs:
  test:
    runs-on: "ubuntu-latest"
    name: pytest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
            cache: 'pip'
            cache-dependency-path: task_a/requirements.txt
        - name: Install dependencies
          run: |
            pip install -r ./task_a/requirements.txt
        - name: Run tests
          continue-on-error: true
          run: |
            pip install pytest pytest-html
            pytest ./task_a/task_a.py --html=report.html --self-contained-html
        - name: Upload report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Report-ubuntu-3.11
            path: report.html
        